version: "2.27.1"
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: react
    container_name: client-app
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    container_name: server-app-container_name
    ports:
      - '3000:3000' 
    depends_on:
      - mongodb 
    external_links:
      - mongodb    
    volumes:
      - ./server:/app
  mongodb:
    image: mongo:latest
    ports:
      - '27018:27017'
